name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd "pg_isready -U $POSTGRES_USER" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5 

    env:
      TESTING: "1"
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: db
      DB_HOST: 127.0.0.1
      GITLAB_BASE_API_URL: ${{ secrets.GITLAB_BASE_API_URL }}
      GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
      GITLAB_PIPELINE_TRIGGER_TOKEN: ${{ secrets.GITLAB_PIPELINE_TRIGGER_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r backend/requirements.txt

    - name: Show environment variables
      run: printenv

    # - name: Set up Alembic and apply migrations
    #   run: |
    #     cd backend
    #     alembic upgrade head

    - name: Run tests
      run: |
        cd backend
        pytest --maxfail=5 --disable-warnings -v
